services:
  development:
    container_name: fcp-mpdp-performance-test-suite-development
    build: .
    depends_on:
      floci-init:
        condition: service_completed_successfully
    volumes:
      - ./reports:/opt/perftest/reports
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SECRET_KEY: test
      AWS_REGION: eu-west-2
      S3_ENDPOINT: 'http://floci:4566'
      RESULTS_OUTPUT_S3_PATH: 's3://fcp-mpdp-performance-test-suite'
      ENVIRONMENT: local
      DOMAIN: host.docker.internal
      LOCAL_PORT: 3000
      PROTOCOL: http
    networks:
      - fcp-mpdp

  floci:
    image: hectorvent/floci:latest
    user: root
    environment:
      FLOCI_HOSTNAME: floci
      FLOCI_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    networks:
      - fcp-mpdp

  floci-init:
    image: amazon/aws-cli
    entrypoint: /bin/sh
    command: /setup/init.sh
    depends_on:
      floci:
        condition: service_started
    environment:
      AWS_ENDPOINT_URL: 'http://floci:4566'
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./floci/init.sh:/setup/init.sh
    networks:
      - fcp-mpdp

networks:
  fcp-mpdp:
    driver: bridge
    name: fcp-mpdp
