services:
  development:
    container_name: fcp-mpdp-performance-test-suite-development
    build: .
    volumes:
      - ./reports:/opt/perftest/reports
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SECRET_KEY: test
      AWS_REGION: eu-west-2
      S3_ENDPOINT: 'http://fcp-mpdp-performance-test-suite-localstack:4566'
      RESULTS_OUTPUT_S3_PATH: 's3://fcp-mpdp-performance-test-suite'
      ENVIRONMENT: local
      DOMAIN: development
      LOCAL_PORT: 3000
      PROTOCOL: http
    networks:
      - fcp-mpdp

  localstack:
    image: localstack/localstack:3.0.2
    container_name: fcp-mpdp-performance-test-suite-localstack
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
      AWS_REGION: eu-west-2
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - fcp-mpdp

networks:
  fcp-mpdp:
    driver: bridge
    name: fcp-mpdp
