services:
  development:
    container_name: fcp-mpdp-performance-test-suite-development
    build: .
    volumes:
      - ./reports:/opt/perftest/reports
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SECRET_KEY: test
      AWS_REGION: eu-west-2
      S3_ENDPOINT: 'http://fcp-mpdp-frontend-localstack:4566'
      RESULTS_OUTPUT_S3_PATH: 's3://fcp-mpdp-performance-test-suite'
      ENVIRONMENT: local
      DOMAIN: development
      LOCAL_PORT: 3000
      PROTOCOL: http
    networks:
      - fcp-mpdp

networks:
  fcp-mpdp:
    driver: bridge
    name: fcp-mpdp
